import type { CarrackDefinition, CarrackTarget, GearDefinition, GearKey, MaterialDefinition, MaterialId, QuestDefinition, ShipBranch } from "@/types";

const req = (gradual: number, equilibrio: number, ascensao: number, bravura: number): Record<CarrackTarget, number> => ({ gradual, equilibrio, ascensao, bravura });

export const CARRACKS: Record<CarrackTarget, CarrackDefinition> = {
  gradual: {
    id: "gradual",
    name: "Carraca de Epheria: Gradual",
    shortName: "Gradual",
    branch: "caravel",
    sourceShip: "Navio Mercante de Epheria",
    role: "Permuta / carga",
    description: "Maior capacidade de carga e inventário. Rota voltada para permuta e logística marítima.",
  },
  equilibrio: {
    id: "equilibrio",
    name: "Carraca de Epheria: Equilíbrio",
    shortName: "Equilíbrio",
    branch: "caravel",
    sourceShip: "Navio Mercante de Epheria",
    role: "Híbrida",
    description: "Equilibra carga, manobrabilidade e combate sem especializar totalmente em uma única função.",
  },
  ascensao: {
    id: "ascensao",
    name: "Carraca de Epheria: Ascensão",
    shortName: "Ascensão",
    branch: "galleass",
    sourceShip: "Contratorpedeiro de Epheria",
    role: "Velocidade / manobra",
    description: "Linha veloz do Contratorpedeiro. O nome atual é Ascensão; algumas fontes antigas ainda exibem Emergência.",
  },
  bravura: {
    id: "bravura",
    name: "Carraca de Epheria: Bravura",
    shortName: "Bravura",
    branch: "galleass",
    sourceShip: "Contratorpedeiro de Epheria",
    role: "Combate",
    description: "Linha de combate do Contratorpedeiro, com foco em poder de fogo e menor tempo de recarga.",
  },
};

export const CARRACK_ORDER: CarrackTarget[] = ["gradual", "equilibrio", "ascensao", "bravura"];

export const MATERIALS: MaterialDefinition[] = [
  {
    id: "redSeaGold",
    name: "Barra de Ouro do Mar Vermelho",
    shortName: "Barra de Ouro do Mar Vermelho",
    icon: "/assets/items/red-sea-gold.png",
    category: "blue-gear",
    required: req(90, 90, 100, 100),
    difficulty: 4,
    crowPrice: 200,
    sources: [
      { type: "daily", label: "[Diário] Para o bem dos jovens Vendedores Lontras", detail: "Recompensa recorrente no Olho de Okilua." },
      { type: "weekly", label: "[Semanal] Caçador de Kandidum da Guilda Lua Minguante", detail: "Escolha de recompensa x4." },
      { type: "barter", label: "Permuta de Mercadoria Marítima [Nível 4]", detail: "Pode aparecer nas rotas de material de navio." },
      { type: "crow", label: "Loja de Moeda Corvo", detail: "200 Moedas Corvo por unidade." },
    ],
  },
  {
    id: "enhancedPlywood",
    name: "Madeira Compensada Revestida de Rubus Aprimorada",
    shortName: "Madeira Compensada Revestida de Rubus Aprimorada",
    icon: "/assets/items/enhanced-plywood.png",
    category: "blue-gear",
    required: req(300, 300, 300, 300),
    difficulty: 3,
    crowPrice: 40,
    sources: [
      { type: "daily", label: "[Permuta][Diário] Ilha de Iliya Agitada II", detail: "Recompensa de missão de permuta." },
      { type: "hunt", label: "Criaturas Marinhas", detail: "Pode ser obtida eliminando criaturas marinhas." },
      { type: "barter", label: "Permuta de Mercadoria Marítima [Nível 4]", detail: "Material de navio em rotas de permuta." },
      { type: "crow", label: "Loja de Moeda Corvo", detail: "40 Moedas Corvo por unidade." },
    ],
  },
  {
    id: "seaweedStalk",
    name: "Caule de Alga Profunda",
    shortName: "Caule de Alga Profunda",
    icon: "/assets/items/seaweed-stalk.png",
    category: "blue-gear",
    required: req(205, 205, 250, 250),
    difficulty: 4,
    crowPrice: 80,
    sources: [
      { type: "daily", label: "[Diário] Para o bem dos jovens Vendedores Lontras", detail: "Recompensa diária no Olho de Okilua." },
      { type: "barter", label: "Permuta de Mercadoria Marítima [Nível 4]", detail: "Pode aparecer nas rotas de material de navio." },
      { type: "crow", label: "Loja de Moeda Corvo", detail: "80 Moedas Corvo por unidade." },
    ],
  },
  {
    id: "greatOceanIron",
    name: "Ferro Forjado Rígido do Oceano",
    shortName: "Ferro Forjado Rígido do Oceano",
    icon: "/assets/items/great-ocean-iron.png",
    category: "blue-gear",
    required: req(150, 150, 150, 150),
    difficulty: 3,
    crowPrice: 130,
    sources: [
      { type: "hunt", label: "Criaturas Marinhas", detail: "Pode ser obtido eliminando criaturas marinhas." },
      { type: "barter", label: "Permuta de Mercadoria Marítima [Nível 4]", detail: "Material de navio em rotas de permuta." },
      { type: "crow", label: "Loja de Moeda Corvo", detail: "130 Moedas Corvo por unidade." },
    ],
  },
  {
    id: "purePearl",
    name: "Cristal de Pérola Pura",
    shortName: "Cristal de Pérola Pura",
    icon: "/assets/items/pure-pearl.png",
    category: "blue-gear",
    required: req(45, 45, 45, 45),
    difficulty: 3,
    crowPrice: 200,
    sources: [
      { type: "daily", label: "[Permuta][Diário] Ilha de Iliya Agitada", detail: "Recompensa de missão de permuta." },
      { type: "hunt", label: "Criaturas Marinhas", detail: "Pode ser obtido eliminando criaturas marinhas." },
      { type: "barter", label: "Permuta de Mercadoria Marítima [Nível 3]", detail: "Pode aparecer nas rotas marítimas." },
      { type: "crow", label: "Loja de Moeda Corvo", detail: "200 Moedas Corvo por unidade." },
    ],
  },
  {
    id: "coxLow",
    name: "Artefato dos Piratas Cox(Negociação de Baixo Nível)",
    shortName: "Artefato dos Piratas Cox(Negociação de Baixo Nível)",
    icon: "/assets/items/cox-low.png",
    category: "blue-gear",
    required: req(60, 60, 60, 60),
    difficulty: 3,
    crowPrice: 120,
    sources: [
      { type: "daily", label: "[Diário] Transporte de Suprimentos", detail: "Recompensa da missão." },
      { type: "barter", label: "Permuta de Mercadoria Marítima [Nível 2]", detail: "Pode aparecer nas rotas marítimas." },
      { type: "hunt", label: "Criaturas Marinhas", detail: "Pode ser obtido eliminando criaturas marinhas." },
      { type: "crow", label: "Loja de Moeda Corvo", detail: "120 Moedas Corvo por unidade." },
    ],
  },
  {
    id: "coxCombat",
    name: "Artefato dos Piratas Cox(Combate)",
    shortName: "Artefato dos Piratas Cox(Combate)",
    icon: "/assets/items/cox-combat.png",
    category: "blue-gear",
    required: req(120, 120, 250, 250),
    difficulty: 5,
    crowPrice: 120,
    sources: [
      { type: "processing", label: "Alquimia Simples — Símbolo de Subjugação dos Piratas Cox", detail: "200 símbolos → 1 Artefato dos Piratas Cox(Combate)." },
      { type: "processing", label: "Alquimia Simples — Canhão Quebrado dos Piratas Cox", detail: "10 canhões quebrados → 1 Artefato dos Piratas Cox(Combate)." },
      { type: "daily", label: "[Diário] Preciso proteger pelo menos o meu corpo", detail: "Recompensa de missão." },
      { type: "weekly", label: "[Semanal] Relatório de Aumento da População", detail: "Recompensa x2." },
      { type: "weekly", label: "[Semanal] Caçador de Dente de Aço Negro da Guilda Lua Minguante", detail: "Escolha de recompensa x6." },
      { type: "hunt", label: "Criaturas Marinhas / Piratas Cox", detail: "Drops usados diretamente ou no processamento." },
      { type: "barter", label: "Permuta [Nível 4] e [Nível 5]", detail: "Pode aparecer nas rotas marítimas." },
      { type: "crow", label: "Loja de Moeda Corvo", detail: "120 Moedas Corvo por unidade." },
    ],
  },
  {
    id: "moonScalePlywood",
    name: "Madeira Compensada Gravada com Escama da Lua",
    shortName: "Madeira Compensada Gravada com Escama da Lua",
    icon: "/assets/items/moon-scale-plywood.png",
    category: "blue-gear",
    required: req(400, 400, 600, 600),
    difficulty: 4,
    crowPrice: 15,
    sources: [
      { type: "processing", label: "Secar — Escama do Khan", detail: "Escama do Khan x1 → 10 unidades." },
      { type: "hunt", label: "Khan, Olho de Okilua", detail: "A Escama do Khan é obtida derrotando Khan." },
      { type: "barter", label: "Permuta de Mercadoria Marítima [Nível 5]", detail: "Pode aparecer nas rotas marítimas." },
      { type: "crow", label: "Loja de Moeda Corvo", detail: "15 Moedas Corvo por unidade." },
    ],
  },
  {
    id: "tideTimber",
    name: "Madeira de Construção com um brilho de onda",
    shortName: "Madeira de Construção com um brilho de onda",
    icon: "/assets/items/tide-timber.png",
    category: "blue-gear",
    required: req(180, 180, 180, 180),
    difficulty: 4,
    crowPrice: 80,
    sources: [
      { type: "processing", label: "Corte — Destroço do Navio Fantasma Naufragado", detail: "Processamento de material obtido no oceano." },
      { type: "daily", label: "[Diário] A guilda não é uma instituição de caridade", detail: "Recompensa de missão." },
      { type: "barter", label: "Permuta de Mercadoria Marítima [Nível 4]", detail: "Pode aparecer nas rotas marítimas." },
      { type: "hunt", label: "Fantasma dos Piratas Cox / Navio Fantasma Naufragado", detail: "Fonte do material usado no processamento." },
      { type: "crow", label: "Loja de Moeda Corvo", detail: "80 Moedas Corvo por unidade." },
    ],
  },
  {
    id: "reefPiece",
    name: "Escultura de Recife Puro",
    shortName: "Escultura de Recife Puro",
    icon: "/assets/items/reef-piece.png",
    category: "blue-gear",
    required: req(180, 180, 180, 180),
    difficulty: 3,
    crowPrice: 30,
    sources: [
      { type: "daily", label: "[Permuta][Diário] Ilha de Iliya Agitada I", detail: "Recompensa de missão de permuta." },
      { type: "hunt", label: "Criaturas Marinhas", detail: "Pode ser obtida eliminando criaturas marinhas." },
      { type: "barter", label: "Permuta de Mercadoria Marítima [Nível 3]", detail: "Pode aparecer nas rotas marítimas." },
      { type: "crow", label: "Loja de Moeda Corvo", detail: "30 Moedas Corvo por unidade." },
    ],
  },
  {
    id: "coxHigh",
    name: "Artefato dos Piratas Cox(Negociação de Alto Nível)",
    shortName: "Artefato dos Piratas Cox(Negociação de Alto Nível)",
    icon: "/assets/items/cox-high.png",
    category: "blue-gear",
    required: req(30, 30, 30, 30),
    difficulty: 4,
    crowPrice: 400,
    sources: [
      { type: "daily", label: "[Permuta][Diário] Ilha de Iliya Agitada II", detail: "Recompensa de missão de permuta." },
      { type: "hunt", label: "Criaturas Marinhas", detail: "Pode ser obtido eliminando criaturas marinhas." },
      { type: "barter", label: "Permuta de Mercadoria Marítima [Nível 4]", detail: "Pode aparecer nas rotas marítimas." },
      { type: "crow", label: "Loja de Moeda Corvo", detail: "400 Moedas Corvo por unidade." },
    ],
  },
  {
    id: "luminousCobalt",
    name: "Barra de Cobalto Brilhante",
    shortName: "Barra de Cobalto Brilhante",
    icon: "/assets/items/luminous-cobalt.png",
    category: "blue-gear",
    required: req(30, 30, 30, 30),
    difficulty: 5,
    crowPrice: 400,
    sources: [
      { type: "barter", label: "Permuta de Mercadoria Marítima [Nível 4]", detail: "Pode aparecer nas rotas marítimas." },
      { type: "hunt", label: "Criaturas Marinhas", detail: "Pode ser obtida eliminando criaturas marinhas." },
      { type: "crow", label: "Loja de Moeda Corvo", detail: "400 Moedas Corvo por unidade." },
    ],
  },
  {
    id: "moonVeinFlax",
    name: "Tecido de Linho com a veia da lua gravada",
    shortName: "Tecido de Linho com a veia da lua gravada",
    icon: "/assets/items/moon-vein-flax.png",
    category: "carrack",
    required: req(180, 180, 210, 180),
    difficulty: 4,
    crowPrice: 40,
    sources: [
      { type: "processing", label: "Secar — Tendão do Khan", detail: "Tendão do Khan x1 → 10 unidades." },
      { type: "daily", label: "[Diário] Caçador de Rei do Mar Jovem da Lua Minguante", detail: "Recompensa x3." },
      { type: "hunt", label: "Khan, Olho de Okilua", detail: "O Tendão do Khan é obtido derrotando Khan." },
      { type: "barter", label: "Permuta de Mercadoria Marítima [Nível 5]", detail: "Pode aparecer nas rotas marítimas." },
      { type: "crow", label: "Loja de Moeda Corvo", detail: "40 Moedas Corvo por unidade." },
    ],
  },
  {
    id: "blueMarineTimber",
    name: "Madeira de Construção Envolto com um Brilho Azul Marinho",
    shortName: "Madeira de Construção Envolto com um Brilho Azul Marinho",
    icon: "/assets/items/blue-marine-timber.png",
    category: "carrack",
    required: req(144, 144, 144, 170),
    difficulty: 4,
    crowPrice: 80,
    sources: [
      { type: "processing", label: "Corte — Estilhaço do Navio Pirata Utilizável", detail: "1 estilhaço → 1 unidade." },
      { type: "daily", label: "[Diário] Bom para você, bom para mim", detail: "Escolha de recompensa x4." },
      { type: "hunt", label: "Navios/Piratas Cox no oceano", detail: "Fonte do Estilhaço do Navio Pirata Utilizável." },
      { type: "barter", label: "Permuta de Mercadoria Marítima [Nível 5]", detail: "Pode aparecer nas rotas marítimas." },
      { type: "crow", label: "Loja de Moeda Corvo", detail: "80 Moedas Corvo por unidade." },
    ],
  },
  {
    id: "saltRock",
    name: "Barra de Sal de Rocha Exuberante",
    shortName: "Barra de Sal de Rocha Exuberante",
    icon: "/assets/items/salt-rock.png",
    category: "carrack",
    required: req(35, 30, 30, 30),
    difficulty: 5,
    crowPrice: 400,
    sources: [
      { type: "hunt", label: "Criaturas Marinhas", detail: "Drop raro de conteúdo oceânico." },
      { type: "barter", label: "Permuta de Mercadoria Marítima [Nível 5]", detail: "Material brilhante de Carraca." },
      { type: "crow", label: "Loja de Moeda Corvo", detail: "400 Moedas Corvo por unidade." },
    ],
  },
  {
    id: "brilliantPearl",
    name: "Cristal de Pérola Brilhante",
    shortName: "Cristal de Pérola Brilhante",
    icon: "/assets/items/brilliant-pearl.png",
    category: "carrack",
    required: req(35, 30, 30, 30),
    difficulty: 5,
    crowPrice: 400,
    sources: [
      { type: "hunt", label: "Criaturas Marinhas", detail: "Drop raro de conteúdo oceânico." },
      { type: "barter", label: "Permuta de Mercadoria Marítima [Nível 5]", detail: "Material brilhante de Carraca." },
      { type: "crow", label: "Loja de Moeda Corvo", detail: "400 Moedas Corvo por unidade." },
    ],
  },
  {
    id: "abyssalEye",
    name: "Olho Abissal",
    shortName: "Olho Abissal",
    icon: "/assets/items/abyssal-eye.png",
    category: "carrack",
    required: req(42, 50, 42, 42),
    difficulty: 5,
    crowPrice: 400,
    sources: [
      { type: "processing", label: "Alquimia Simples — Gema do Mar Profundo", detail: "Gema do Mar Profundo x2 → 1 Olho Abissal." },
      { type: "daily", label: "[Diário] Caçador de Rei do Mar Jovem da Lua Minguante", detail: "Recompensa x1." },
      { type: "weekly", label: "[Semanal] Caçador de Nineshark da Guilda Lua Minguante", detail: "Escolha de recompensa x2." },
      { type: "barter", label: "Permuta de Mercadoria Marítima [Nível 5]", detail: "Pode aparecer nas rotas marítimas." },
      { type: "crow", label: "Loja de Moeda Corvo", detail: "400 Moedas Corvo por unidade." },
    ],
  },
  {
    id: "waveStone",
    name: "Pedra Negra da Onda",
    shortName: "Pedra Negra da Onda",
    icon: "/assets/items/wave-stone.png",
    category: "enhancement",
    required: req(0, 0, 0, 0),
    difficulty: 3,
    sources: [
      { type: "weekly", label: "Semanais do Olho de Okilua", detail: "Várias semanais oferecem opção de x60." },
      { type: "crow", label: "Loja de Moeda Corvo", detail: "Baús/pacotes semanais conforme a loja atual." },
    ],
  },
];

export const MATERIAL_BY_ID = Object.fromEntries(MATERIALS.map((item) => [item.id, item])) as Record<MaterialId, MaterialDefinition>;

const sharedBlueIcons = {
  figurehead: { blue: "/assets/gear/figurehead-blue.png", base: "/assets/gear/figurehead-base.png" },
  plating: { blue: "/assets/gear/plating-blue.png", base: "/assets/gear/plating-base.png" },
  cannon: { blue: "/assets/gear/cannon-blue.png", base: "/assets/gear/cannon-base.png" },
  sail: { blue: "/assets/gear/sail-blue.png", base: "/assets/gear/sail-base.png" },
};

export const GEAR_SETS: Record<ShipBranch, Record<GearKey, GearDefinition>> = {
  caravel: {
    figurehead: {
      name: "Navio Mercante de Epheria: Proa de Dragão Negro",
      icon: sharedBlueIcons.figurehead.blue,
      base: "Navio Mercante de Epheria: Proa de Latão +10",
      baseIcon: sharedBlueIcons.figurehead.base,
      materials: { redSeaGold: 50, enhancedPlywood: 300, seaweedStalk: 125, greatOceanIron: 150 },
    },
    plating: {
      name: "Navio Mercante de Epheria: Casco Refinado",
      icon: sharedBlueIcons.plating.blue,
      base: "Navio Mercante de Epheria: Casco Aprimorado +10",
      baseIcon: sharedBlueIcons.plating.base,
      materials: { purePearl: 45, coxLow: 60, coxCombat: 60, moonScalePlywood: 200 },
    },
    cannon: {
      name: "Navio Mercante de Epheria: Canhão Meina",
      icon: sharedBlueIcons.cannon.blue,
      base: "Navio Mercante de Epheria: Canhão Verisha +10",
      baseIcon: sharedBlueIcons.cannon.base,
      materials: { tideTimber: 180, coxCombat: 60, moonScalePlywood: 200, reefPiece: 180 },
    },
    sail: {
      name: "Navio Mercante de Epheria: Vela de Camada",
      icon: sharedBlueIcons.sail.blue,
      base: "Navio Mercante de Epheria: Vela de Vento Branca +10",
      baseIcon: sharedBlueIcons.sail.base,
      materials: { redSeaGold: 40, coxHigh: 30, seaweedStalk: 80, luminousCobalt: 30 },
    },
  },
  galleass: {
    figurehead: {
      name: "Contratorpedeiro de Epheria: Proa de Dragão Negro",
      icon: sharedBlueIcons.figurehead.blue,
      base: "Contratorpedeiro de Epheria: Proa de Quartzo Branco +10",
      baseIcon: sharedBlueIcons.figurehead.base,
      materials: { redSeaGold: 50, enhancedPlywood: 300, seaweedStalk: 125, greatOceanIron: 150 },
    },
    plating: {
      name: "Contratorpedeiro de Epheria: Casco Refinado",
      icon: sharedBlueIcons.plating.blue,
      base: "Contratorpedeiro de Epheria: Casco Aprimorado +10",
      baseIcon: sharedBlueIcons.plating.base,
      materials: { purePearl: 45, coxLow: 60, coxCombat: 125, moonScalePlywood: 300 },
    },
    cannon: {
      name: "Contratorpedeiro de Epheria: Canhão Meina",
      icon: sharedBlueIcons.cannon.blue,
      base: "Contratorpedeiro de Epheria: Canhão Verisha +10",
      baseIcon: sharedBlueIcons.cannon.base,
      materials: { tideTimber: 180, coxCombat: 125, moonScalePlywood: 300, reefPiece: 180 },
    },
    sail: {
      name: "Contratorpedeiro de Epheria: Vela de Camada",
      icon: sharedBlueIcons.sail.blue,
      base: "Contratorpedeiro de Epheria: Vela de Vento Branca +10",
      baseIcon: sharedBlueIcons.sail.base,
      materials: { redSeaGold: 50, coxHigh: 30, seaweedStalk: 125, luminousCobalt: 30 },
    },
  },
};

export const QUESTS: QuestDefinition[] = [
  {
    id: "daily-young-sea-king",
    cadence: "daily",
    title: "Caçador de Rei do Mar Jovem da Lua Minguante",
    npc: "Ravikel",
    location: "Olho de Okilua",
    objective: "Eliminar Rei do Mar Jovem na região indicada.",
    rewards: ["Madeira Compensada Gravada com Escama da Lua x10", "Tecido de Linho com a veia da lua gravada x3", "Olho Abissal x1", "Moeda de Comemoração do Okilua x3"],
    recommendedFor: ["moonScalePlywood", "moonVeinFlax", "abyssalEye"],
    priority: 5,
    source: "BDO Codex / conteúdo atual do Olho de Okilua",
  },
  {
    id: "daily-good-for-you",
    cadence: "daily",
    title: "Bom para você, bom para mim",
    npc: "Soldado da Guilda Lua Minguante",
    location: "Olho de Okilua",
    objective: "Eliminar Perseguidor do Oceano ao noroeste do Olho de Okilua.",
    rewards: ["Moeda de Comemoração do Okilua x1", "Escolha: Madeira de Construção Envolto com um Brilho Azul Marinho x4 ou Cola com traços de onda x1"],
    recommendedFor: ["blueMarineTimber"],
    priority: 5,
    source: "BDO Codex",
  },
  {
    id: "daily-cox-body",
    cadence: "daily",
    title: "Preciso proteger pelo menos o meu corpo",
    npc: "Olho de Okilua",
    location: "Olho de Okilua",
    objective: "Concluir a missão diária contra Piratas Cox.",
    rewards: ["Artefato dos Piratas Cox(Combate)"],
    recommendedFor: ["coxCombat"],
    priority: 5,
    source: "BDO Codex",
  },
  {
    id: "daily-supplies",
    cadence: "daily",
    title: "Transporte de Suprimentos",
    npc: "Olho de Okilua",
    location: "Olho de Okilua",
    objective: "Concluir a missão diária de transporte.",
    rewards: ["Artefato dos Piratas Cox(Negociação de Baixo Nível)"],
    recommendedFor: ["coxLow"],
    priority: 4,
    source: "BDO Codex",
  },
  {
    id: "daily-iliya-i",
    cadence: "daily",
    title: "[Permuta][Diário] Ilha de Iliya Agitada I",
    npc: "Ilha de Iliya",
    location: "Ilha de Iliya",
    objective: "Concluir a missão diária de permuta.",
    rewards: ["Escultura de Recife Puro"],
    recommendedFor: ["reefPiece"],
    priority: 4,
    source: "BDO Codex",
  },
  {
    id: "daily-iliya-ii",
    cadence: "daily",
    title: "[Permuta][Diário] Ilha de Iliya Agitada II",
    npc: "Ilha de Iliya",
    location: "Ilha de Iliya",
    objective: "Concluir a missão diária de permuta.",
    rewards: ["Madeira Compensada Revestida de Rubus Aprimorada", "Artefato dos Piratas Cox(Negociação de Alto Nível)"],
    recommendedFor: ["enhancedPlywood", "coxHigh"],
    priority: 4,
    source: "BDO Codex",
  },
  {
    id: "weekly-kandidum",
    cadence: "weekly",
    title: "Caçador de Kandidum da Guilda Lua Minguante",
    npc: "Ravikel",
    location: "Olho de Okilua",
    objective: "Eliminar Kandidum x1.",
    rewards: ["Moeda Corvo x500", "Escolha: Pedra Negra da Onda x60 / Barra de Ouro do Mar Vermelho x4 / Madeira de Construção com um brilho de onda x1"],
    recommendedFor: ["redSeaGold", "tideTimber", "waveStone"],
    priority: 5,
    source: "Notas do Oceano / BDO Codex",
  },
  {
    id: "weekly-nineshark",
    cadence: "weekly",
    title: "Caçador de Nineshark da Guilda Lua Minguante",
    npc: "Ravikel",
    location: "Olho de Okilua",
    objective: "Eliminar Nineshark x1.",
    rewards: ["Moeda Corvo x500", "Escolha: Pedra Negra da Onda x60 / Olho Abissal x2 / Suporte com acabamento elaborado x1"],
    recommendedFor: ["abyssalEye", "waveStone"],
    priority: 5,
    source: "Notas do Oceano / BDO Codex",
  },
  {
    id: "weekly-black-rust",
    cadence: "weekly",
    title: "Caçador de Dente de Aço Negro da Guilda Lua Minguante",
    npc: "Ravikel",
    location: "Olho de Okilua",
    objective: "Eliminar Dente de Aço Negro x1.",
    rewards: ["Moeda Corvo x500", "Escolha: Pedra Negra da Onda x60 / Artefato dos Piratas Cox(Combate) x6 / Cola com traços de onda x1"],
    recommendedFor: ["coxCombat", "waveStone"],
    priority: 5,
    source: "Notas do Oceano / BDO Codex",
  },
  {
    id: "weekly-young-sea-monsters",
    cadence: "weekly",
    title: "Relatório de Aumento da População",
    npc: "Soldado próximo de Sherri Ricky",
    location: "Olho de Okilua",
    objective: "Eliminar Rei do Mar Jovem x20.",
    rewards: ["Artefato dos Piratas Cox(Combate) x2", "EXP de Navegação"],
    recommendedFor: ["coxCombat"],
    priority: 4,
    source: "BDO Codex",
  },
];

export const SOURCES = [
  { label: "Pearl Abyss — 4 Carracas (27/08/2026)", href: "https://www.sa.playblackdesert.com/pt-br/News/Detail?countryType=pt-br&groupContentNo=8511" },
  { label: "Guia oficial — Melhorias em Navios", href: "https://www.sa.playblackdesert.com/pt-br/Wiki?wikiNo=291" },
  { label: "Atualização — Missões do Oceano", href: "https://www.sa.playblackdesert.com/pt-br/News/Detail?groupContentNo=5779" },
  { label: "Atualização — Loja Corvo 21/05/2026", href: "https://www.sa.playblackdesert.com/pt-BR/News/Detail?groupContentNo=7988" },
  { label: "BDO Codex — banco de itens, receitas e missões", href: "https://bdocodex.com/pt/" },
  { label: "Black Desert Foundry — Epheria Carrack Guide", href: "https://www.blackdesertfoundry.com/epheria-carrack-guide/" },
];
